name: Tests on each push
on: [push]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11.4
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -coverprofile coverage.txt -cover ./...
    - name: Upload tests coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
